# mysql数据库连接
spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/network_disk?serverTimezone=GMT%2B8
      username: root
      password: 12345678
      # 数据库连接池最大值
      max-active: 20
      # 数据库连接池初始值
      initial-size: 5
      # 数据库连接池最小空闲值
      min-idle: 5
      # 池中空闲连接大于minIdle且连接空闲时间大于该值，则关闭该连接，单位毫秒(5分钟，默认30分钟)
      min-evictable-idle-time-millis: 300000
      # 获取连接时最大等待时间，单位毫秒(1分钟)
      max-wait: 60000
      # 借用连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-return: false
      # 连接空闲时检测，如果连接空闲时间大于timeBetweenEvictionRunsMillis指定的毫秒，执行validationQuery指定的SQL来检测连接是否有效
      test-while-idle: true
      # 空闲连接检查、废弃连接清理、空闲连接池大小调整的操作时间间隔，单位是毫秒(1分钟)
      time-between-eviction-runs-millis: 60000
      # 检测连接是否有效时执行的sql命令
      validation-query: select 1

      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      filters: stat,wall
      stat-view-servlet:
        enabled: true
        login-password: admin
        login-username: admin
        reset-enable: false
        url-pattern: /druid/*
      web-stat-filter:
        enabled: true
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        url-pattern: /*

#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/network_disk?serverTimezone=GMT%2B8
#    username: root
#    password: 12345678

# mybatis-plus相关配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true





